// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALhwHAuGaWapnf2Ktz4v_8O1WNCs49tA8',
    appId: '1:28289929321:web:5f5a3b942de1b86fc792f8',
    messagingSenderId: '28289929321',
    projectId: 'e-learning-c8246',
    authDomain: 'e-learning-c8246.firebaseapp.com',
    storageBucket: 'e-learning-c8246.appspot.com',
    measurementId: 'G-0SRKM53ESD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByE8T4EfGPqWlK7uY4KakUAd9hGq65EcQ',
    appId: '1:28289929321:android:f00a0eedf34118dcc792f8',
    messagingSenderId: '28289929321',
    projectId: 'e-learning-c8246',
    storageBucket: 'e-learning-c8246.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyV8Sta92bLLg7jUq5O2VTh0CW2TOx8QA',
    appId: '1:28289929321:ios:dfd20d7384a0664bc792f8',
    messagingSenderId: '28289929321',
    projectId: 'e-learning-c8246',
    storageBucket: 'e-learning-c8246.appspot.com',
    iosClientId: '28289929321-57r6iri9j8v0ad49bk66hd5o7j2hba8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyV8Sta92bLLg7jUq5O2VTh0CW2TOx8QA',
    appId: '1:28289929321:ios:dfd20d7384a0664bc792f8',
    messagingSenderId: '28289929321',
    projectId: 'e-learning-c8246',
    storageBucket: 'e-learning-c8246.appspot.com',
    iosClientId: '28289929321-57r6iri9j8v0ad49bk66hd5o7j2hba8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearning',
  );
}
